# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AIPrN@PVAMU
email: sekim@pvamu.edu
description: >- # this means to ignore newlines until "baseurl:"
  This initiative aims to increase and diversify the future workforce in 
  Artificial Intelligence for Precision Nutrition Science Research (AIPrN). 
  Advancing research in AIPrN will lead to the development of innovative 
  solutions to promote nutrition and health equity among underserved populations, 
  particularly in the context of food insecurity, obesity, type 2 diabetes, 
  cardiovascular diseases, and cancer. 
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dolchan.github.io/aiprnt32/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aiprn_pvamu
github_username:  aiprn_pvamu

# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache


# skin
# minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "aqua" 


# repository
repository: "dolchan/aiprnt32"


# teaser
teaser: /assets/images/500x300.png


# breadcrumb
# breadcrumbs: true  # disabled by default


# Pages
include: ["_pages"]


# Post dates
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      # read_time: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      # read_time: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
